
id: myflow
namespace: company.team

description: |
  This flow installs the pip packages required for image processing in a Docker container, 
  then uses Kestra's Python library to extract pixels to a string.

inputs:
  - id: file
    type: STRING

  - id: payload
    type: JSON
    defaults: |
      {"image_string": "Kestra Pen"}

tasks:

  - id: extract_pixels_to_string
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
      include:
        - extract_pixels_to_string.py
    containerImage: python:slim
    warningOnStdErr: false
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - python extract_pixels_to_string.py
    env:
      KESTRA_INPUT_FILE_BASE64: "{{ trigger.body.file }}"
      KESTRA_WORKSPACE_ID: "{{ trigger.body.workspaceId }}"
      S3_BUCKET_NAME:  localstack_kestra
      AWS_ACCESS_KEY_ID:  test
      AWS_SECRET_ACCESS_KEY:  test
      S3_REGION: ap-south-1
      LOCALSTACK_S3_URL: http://localhost:4572


  - id: send_data
    type: io.kestra.plugin.core.http.Request
    uri: http://host.docker.internal:3010/kestra/image-string
    method: POST
    contentType: application/json
    body: "{{ inputs.payload }}"

  - id: log_image_data
    type: io.kestra.plugin.core.log.Log
    message: "Image String: {{ outputs.extract_pixels_to_string }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r

