services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: img_vr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localstack_nt

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    environment:
      KESTRA_DATABASE_URL: jdbc:postgresql://postgres:5432/kestra
      KESTRA_DATABASE_USERNAME: admin
      KESTRA_DATABASE_PASSWORD: admin
    user: root
    ports:
      - "8080:8080"
      - "3002:3002"
    command: server local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - postgres
    networks:
      - localstack_nt

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566" #localstack
      - "8081:8080"
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - localstack_nt

volumes:
  postgres_data:
  localstack_data:

networks:
  localstack_nt:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"