export const S3_BUCKET_NAME=  "localstack_kestra"
export const AWS_ACCESS_KEY_ID=  "test"
export const AWS_SECRET_ACCESS_KEY=  "test"
export const S3_REGION= "ap-south-1"
export const LOCALSTACK_S3_URL= "http://localhost:4572"
